name: build container image

on:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  pipeline:
    name: Skaffold Pipeline
    runs-on: ubuntu-20.04
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Skaffold build pipeline as action
        uses: hiberbee/github-action-skaffold@1.19.0
        with:
          command: build
          profile: develop
          repository: ghcr.io/${{ github.repository_owner }}/repostkun_beta
